### ISSUE TITLE
Missing plural form

### ISSUE THREAD

**Issue by mKoonrad** [ProtonVPN/vpncore#1]
https://github.com/ProtonVPN/vpncore/blob/8e4f1bb90c517350d60688b2d21bc6b3af7afc0d/Source/Localization/pl.lproj/Localizable.strings#L155

https://github.com/ProtonVPN/vpncore/blob/8e4f1bb90c517350d60688b2d21bc6b3af7afc0d/Source/Localization/pl.lproj/Localizable.strings#L868

You should add plural form for few and many form.

**Comment by jaroslavas** [comment]
Thank You. The issue will be fixed in the next release.
